# 災害救助法適用事例の分析

災害救助法の適用事例のCSVを、地図で落とし込めるように編集

In [1]:
import pandas as pd
import geopandas as gpd
import os
import json

In [2]:
# 災害救助法適用事例をロード
disaster_cases = pd.read_csv(os.path.join('data', '災害救助法適用事例', '災害救助法適用事例.csv'), encoding='shift_jis')

In [3]:
disaster_cases.head()

    年度  西暦年度         決定日         適用日       災害タイトル 災害種別 適用基準 都道府県   市町村
0  H26  2014  2014-07-09  2014-07-09   平成26年台風第８号   台風   4号  長野県  南木曽町
1  H26  2014  2014-07-14  2014-07-09   平成26年台風第８号   台風   1号  山形県   南陽市
2  H26  2014  2014-08-08  2014-08-03  平成26年台風第12号   台風   1号  高知県   いの町
3  H26  2014  2014-08-09  2014-08-09  平成26年台風第11号   台風   4号  高知県   高知市
4  H26  2014  2014-08-09  2014-08-09  平成26年台風第11号   台風   4号  高知県   大豊町

In [4]:
print([x for x in disaster_cases['災害タイトル'].unique()])

['平成26年台風第８号', '平成26年台風第12号', '平成26年台風第11号', '平成26年8月15日からの大雨', '平成26年8月19日からの大雨', '御嶽山噴火による被害', '長野県神城断層地震', '12月5日からの大雪', '口永良部島噴火', '平成27年９月関東・東北豪雨', '平成27年台風第21号', '平成28年熊本地震', '平成28年台風第10号', '平成28年鳥取県中部地震', '平成28年新潟県糸魚川市における大規模火災（住宅火災）', '平成29年7月九州北部豪雨', '平成29年7月22日からの大雨', '平成29年台風第18号', '平成29年台風第21号', '平成30年2月4日からの大雪', '平成29年度豪雪', '平成30年大阪府北部を震源とする地震', '平成30年７月豪雨', '平成30年８月30日からの大雨', '平成30年北海道胆振東部地震', '令和元年８月の前線に伴う大雨', '令和元年台風第15号', '令和元年台風第15号（停電）', '令和元年台風第19号', '令和２年７月３日からの大雨', '令和２年台風第14号', '令和２年12月16日からの大雪（交通障害）', '令和３年１月７日からの大雪', '令和３年福島県沖を震源とする地震', '令和３年栃木県足利市における大規模火災（山林火災）', '令和３年新潟県糸魚川市における地滑り', '島根県松江市における大規模火災（住宅火災）', '令和３年７月１日からの大雨', '台風第９号から変わった温帯低気圧に伴う大雨', '令和３年８月１１日からの大雨', '令和３年長野県茅野市において発生した土石流', '令和４年福島県沖を震源とする地震', '令和４年７月14日からの大雨', '令和４年８月３日からの大雨', '令和４年８月９日からの大雨', '令和４年台風第14号', '令和４年台風第15号', '令和４年12月17日からの大雪（交通障害等）', '令和４年12月22日からの大雪（長期停電）', '令和４年山形県鶴岡市の土砂崩れ', '令和５年１月24日からの大雪（交通障害）', '令和５年石川県能登地方を震源とする地震', '令和５年梅雨前線による大雨及び台風第２号', '令和５年６月29日からの大雨', '令和５年７月７日からの大雨', '令和５年台風第６号（停電）', '令和５年台風第７号', '令和５年台風第13号', '令和６年能登半島地震', '令和６年１月23日からの大雪（交通障害）', '令和６年７月９日からの大雨', '令和６年７月25日からの大雨', '令和６年台風第10号', '低気圧と前線による大雨', '令和６年11月８日からの大雨', '令和６年12月28日からの大雪', '流域下水道管の破損に起因する道路陥没事故', '令和７年２月４日からの大雪', '令和７年２月17日からの日本海側を中心とした大雪', '令和７年岩手県大船渡市における大規模火災（森林火災からの住家被害）', 'トカラ列島近海を震源とする地震', '令和７年台風第８号に伴う災害', '令和７年カムチャツカ半島付近の地震に伴う津波', '令和７年８月６日からの低気圧と前線による大雨', '令和７年８月20日からの大雨', '令和７年台風12号', '令和７年９月２日からの大雨', '令和７年台風第15号等', '令和７年９月12日からの大雨', '令和７年台風第22号', '令和７年11月18日大分市佐賀関の大規模火災', '令和７年青森県東方沖を震源とする地震', '令和８年１月21日からの大雪']

In [5]:
# 日付を日付形式に変換
disaster_cases['決定日'] = pd.to_datetime(disaster_cases['決定日'])
disaster_cases['適用日'] = pd.to_datetime(disaster_cases['適用日'])

In [6]:
disaster_cases['災害種別'].value_counts()

災害種別
台風      934
大雨      432
地震      149
大雪      146
津波      118
火災        5
噴火        3
地滑り       1
土石流       1
土砂崩れ      1
道路陥没      1
Name: count, dtype: int64

In [7]:
disaster_cases.dtypes

年度                object
西暦年度               int64
決定日       datetime64[ns]
適用日       datetime64[ns]
災害タイトル            object
災害種別              object
適用基準              object
都道府県              object
市町村               object
dtype: object

## 自治体境界データを編集

In [24]:
japan_map = gpd.read_file(os.path.join('data', 'japan_ver85','japan_ver85','japan_ver85.shp'))

In [25]:
japan_map.head()

,JCODE,KEN,SICHO,GUN,SEIREI,SIKUCHOSON,CITY_ENG,P_NUM,H_NUM,Shape_Leng,Shape_Area,geometry
0,01101,北海道,石狩振興局,None,札幌市,中央区,"Sapporo-shi, Chuo-ku",248680,141429,0.542590,0.005128,"POLYGON ((141.34233 43.06682, 141.3552 43.0685..."
1,01102,北海道,石狩振興局,None,札幌市,北区,"Sapporo-shi, Kita-ku",289323,139675,0.567773,0.007031,"POLYGON ((141.40839 43.18395, 141.40427 43.182..."
2,01103,北海道,石狩振興局,None,札幌市,東区,"Sapporo-shi, Higashi-ku",265379,131188,0.397203,0.006289,"POLYGON ((141.44698 43.15513, 141.4486 43.1532..."
3,01104,北海道,石狩振興局,None,札幌市,白石区,"Sapporo-shi, Shiroishi-ku",211835,108233,0.308211,0.003815,"POLYGON ((141.46569 43.1, 141.46812 43.09704, ..."
4,01105,北海道,石狩振興局,None,札幌市,豊平区,"Sapporo-shi, Toyohira-ku",225298,118650,0.428316,0.005101,"POLYGON ((141.38479 43.0466, 141.38558 43.0472..."

In [26]:
# 政令指定都市が区ごとに別れているため、市全体を一つのポリゴンとしてまとめる
# SEIREI値を持つ行と持たない行を分離する
japan_map_with_seirei = japan_map[japan_map['SEIREI'].notna()].copy()
japan_map_without_seirei = japan_map[japan_map['SEIREI'].isna()].copy()

# 政令市フラグ
japan_map_with_seirei['seirei_flag'] = 1
japan_map_without_seirei['seirei_flag'] = 0

# 政令市の情報を市区町村列にコピー
japan_map_with_seirei['SIKUCHOSON'] = japan_map_with_seirei['SEIREI'] + japan_map_with_seirei['SIKUCHOSON']

# 政令市の一覧を取得
seirei_list = japan_map_with_seirei[['KEN','SEIREI']].drop_duplicates().agg(' '.join, axis=1).to_list()

# # 同じSEIREI値を持つポリゴンを統合する
# japan_map_merged_with_seirei = japan_map_with_seirei.dissolve(by='SEIREI', aggfunc='first')

# # インデックスをリセットしてSEIREIを列として再度作成する
# japan_map_merged_with_seirei = japan_map_merged_with_seirei.reset_index()

# # SEIREIの値をSIKUCHOSONにコピーする
# japan_map_merged_with_seirei['SIKUCHOSON'] = japan_map_merged_with_seirei['SEIREI']

# # CITY_ENG列で、カンマ以降のすべてを省略する（区が入っている部分を消去）
# japan_map_merged_with_seirei['CITY_ENG'] = japan_map_merged_with_seirei['CITY_ENG'].str.split(',').str[0]

# # JCODEの最後の文字を0に置き換える（区の自治体コードとなっているのを市の自治体コードに変換する）
# japan_map_merged_with_seirei['JCODE'] = japan_map_merged_with_seirei['JCODE'].str[:-1] + '0'

# 政令市部分とそれ以外を統合し、SEIREI列を削除する
# japan_map = pd.concat([japan_map_merged_with_seirei, japan_map_without_seirei], ignore_index=True)

japan_map = pd.concat([japan_map_with_seirei, japan_map_without_seirei], ignore_index=True)
japan_map = japan_map.drop(columns=['SEIREI'])

# JCODE列でソートする
japan_map.sort_values('JCODE', inplace=True)

# 不要な列を削除
japan_map.drop(columns=['P_NUM', 'H_NUM', 'Shape_Area', 'Shape_Leng'], inplace=True)

In [27]:
japan_map.head()

,JCODE,KEN,SICHO,GUN,SIKUCHOSON,CITY_ENG,geometry,seirei_flag
0,01101,北海道,石狩振興局,None,札幌市中央区,"Sapporo-shi, Chuo-ku","POLYGON ((141.34233 43.06682, 141.3552 43.0685...",1
1,01102,北海道,石狩振興局,None,札幌市北区,"Sapporo-shi, Kita-ku","POLYGON ((141.40839 43.18395, 141.40427 43.182...",1
2,01103,北海道,石狩振興局,None,札幌市東区,"Sapporo-shi, Higashi-ku","POLYGON ((141.44698 43.15513, 141.4486 43.1532...",1
3,01104,北海道,石狩振興局,None,札幌市白石区,"Sapporo-shi, Shiroishi-ku","POLYGON ((141.46569 43.1, 141.46812 43.09704, ...",1
4,01105,北海道,石狩振興局,None,札幌市豊平区,"Sapporo-shi, Toyohira-ku","POLYGON ((141.38479 43.0466, 141.38558 43.0472...",1

## データの結合

データの結合ができる状態になっていることを確認したうえで、市区町村ごとに災害データを整理

In [28]:
# 表記揺れを修正
japan_map['SIKUCHOSON'] = japan_map['SIKUCHOSON'].replace({
    '須惠町': '須恵町',
})
disaster_cases['市町村'] = disaster_cases['市町村'].replace({
    '塩竃市': '塩竈市',
    '篠山市': '丹波篠山市', # 2020年に篠山市は丹波篠山市に改称
    '飛?市': '飛騨市',
    '桧枝岐村': '檜枝岐村',
    '梼原町': '檮原町',
})

In [29]:
# 自治体名でマージするためのキーを作成
disaster_cases['prefcity'] = disaster_cases[['都道府県','市町村']].agg(' '.join, axis=1)
japan_map['prefcity'] = japan_map[['KEN','SIKUCHOSON']].agg(' '.join, axis=1)

In [30]:
# 自治体名でマージできることを確認
merged = pd.merge(disaster_cases, japan_map[['prefcity', 'geometry']], on='prefcity', how='left', indicator=True)

In [31]:
merged[merged['_merge'] == 'left_only']['prefcity'].unique()

array(['広島県 広島市', '宮城県 仙台市', '熊本県 全市町村', '大阪府 大阪市', '岡山県 岡山市', '北海道 全市町村',
       '神奈川県 川崎市', '神奈川県 相模原市', '埼玉県 さいたま市', '福岡県 北九州市', '福岡県 福岡市',
       '熊本県 熊本市', '静岡県 静岡市', '静岡県 浜松市', '新潟県 新潟市'], dtype=object)

In [85]:
# 災害データベースを作成
disaster_database = disaster_cases.groupby(['西暦年度','災害タイトル','災害種別'])['適用日'].min().reset_index()
disaster_database['適用日'] = disaster_database['適用日'].dt.strftime('%Y-%m-%d')  # 日付を文字列に変換
disaster_database_dict = disaster_database.to_dict('index')
disaster_database['ID'] = disaster_database.index

In [86]:
# IDを付与
disaster_cases_iter = disaster_cases.merge(disaster_database.drop('適用日', axis=1), on=['西暦年度','災害タイトル','災害種別'], how='left')

In [87]:
disaster_cases_iter.head()

,年度,西暦年度,決定日,適用日,災害タイトル,災害種別,適用基準,都道府県,市町村,prefcity,ID
0,H26,2014,2014-07-09,2014-07-09,平成26年台風第８号,台風,4号,長野県,南木曽町,長野県 南木曽町,5
1,H26,2014,2014-07-14,2014-07-09,平成26年台風第８号,台風,1号,山形県,南陽市,山形県 南陽市,5
2,H26,2014,2014-08-08,2014-08-03,平成26年台風第12号,台風,1号,高知県,いの町,高知県 いの町,4
3,H26,2014,2014-08-09,2014-08-09,平成26年台風第11号,台風,4号,高知県,高知市,高知県 高知市,3
4,H26,2014,2014-08-09,2014-08-09,平成26年台風第11号,台風,4号,高知県,大豊町,高知県 大豊町,3

In [88]:
japan_map.head()

,JCODE,KEN,SICHO,GUN,SIKUCHOSON,CITY_ENG,geometry,seirei_flag,prefcity
0,01101,北海道,石狩振興局,None,札幌市中央区,"Sapporo-shi, Chuo-ku","POLYGON ((141.34233 43.06682, 141.3552 43.0685...",1,北海道 札幌市中央区
1,01102,北海道,石狩振興局,None,札幌市北区,"Sapporo-shi, Kita-ku","POLYGON ((141.40839 43.18395, 141.40427 43.182...",1,北海道 札幌市北区
2,01103,北海道,石狩振興局,None,札幌市東区,"Sapporo-shi, Higashi-ku","POLYGON ((141.44698 43.15513, 141.4486 43.1532...",1,北海道 札幌市東区
3,01104,北海道,石狩振興局,None,札幌市白石区,"Sapporo-shi, Shiroishi-ku","POLYGON ((141.46569 43.1, 141.46812 43.09704, ...",1,北海道 札幌市白石区
4,01105,北海道,石狩振興局,None,札幌市豊平区,"Sapporo-shi, Toyohira-ku","POLYGON ((141.38479 43.0466, 141.38558 43.0472...",1,北海道 札幌市豊平区

In [89]:
japan_map['prefcity']

0       北海道 札幌市中央区
1        北海道 札幌市北区
2        北海道 札幌市東区
3       北海道 札幌市白石区
4       北海道 札幌市豊平区
           ...
804      千葉県 所属不明地
867      東京都 所属不明地
1210     愛知県 所属不明地
1864    鹿児島県 所属不明地
1906     沖縄県 所属不明地
Name: prefcity, Length: 1907, dtype: object

In [90]:
japan_map['JCODE'].dropna().unique()

array(['01101', '01102', '01103', ..., '47375', '47381', '47382'],
      dtype=object)

In [91]:
# 市町村ごとの災害一覧と集計をdictで作成
disaster_summary = {}
disaster_types = disaster_cases['災害種別'].unique()

for jcode in japan_map['JCODE'].dropna().unique():
    disaster_summary[jcode] = {
        'name': japan_map[japan_map['JCODE'] == jcode]['prefcity'].values[0],
        'disaster_id': [],
        'disaster_count': {disaster_type: 0 for disaster_type in disaster_types}
    }

# 災害データベースに発生自治体の一覧を追加
for item in disaster_database_dict.values():
    item['municipalities'] = []

# 履歴を1行ずつ処理していく
for i, row in disaster_cases_iter.iterrows():
    prefcity = row['prefcity']
    disaster_id = row['ID']
    disaster_type = row['災害種別']
    
    if '全市町村' in prefcity:
        # 県内全域に適用される災害の場合、県内のすべての市町村に災害IDを追加し、災害種別のカウントを増やす
        prefecture = row['都道府県']
        for jcode, summary in disaster_summary.items():
            if summary['name'].startswith(prefecture):
                disaster_summary[jcode]['disaster_id'].append(disaster_id)
                disaster_summary[jcode]['disaster_count'][disaster_type] += 1
                disaster_database_dict[disaster_id]['municipalities'].append(jcode) 
    elif prefcity in seirei_list:
        # 政令市の場合、すべての区に災害IDを追加し、災害種別のカウントを増やす
        for jcode, summary in disaster_summary.items():
            if summary['name'].startswith(prefcity):
                disaster_summary[jcode]['disaster_id'].append(disaster_id)
                disaster_summary[jcode]['disaster_count'][disaster_type] += 1
                disaster_database_dict[disaster_id]['municipalities'].append(jcode)
    else:
        # 通常の市町村の場合、災害IDを追加し、災害種別のカウントを増やす
        for jcode, summary in disaster_summary.items():
            if summary['name'] == prefcity:
                disaster_summary[jcode]['disaster_id'].append(disaster_id)
                disaster_summary[jcode]['disaster_count'][disaster_type] += 1
                disaster_database_dict[disaster_id]['municipalities'].append(jcode)

# 災害の合計値
for jcode, summary in disaster_summary.items():
    summary['disaster_count']['合計'] = sum(summary['disaster_count'].values())

In [92]:
disaster_database_dict

{0: {'西暦年度': 2014,
  '災害タイトル': '12月5日からの大雪',
  '災害種別': '大雪',
  '適用日': '2014-12-08',
  'municipalities': ['36208', '36468', '36489']},
 1: {'西暦年度': 2014,
  '災害タイトル': '平成26年8月15日からの大雨',
  '災害種別': '大雨',
  '適用日': '2014-08-17',
  'municipalities': ['26201', '28223']},
 2: {'西暦年度': 2014,
  '災害タイトル': '平成26年8月19日からの大雨',
  '災害種別': '大雨',
  '適用日': '2014-08-20',
  'municipalities': ['34101',
   '34102',
   '34103',
   '34104',
   '34105',
   '34106',
   '34107',
   '34108']},
 3: {'西暦年度': 2014,
  '災害タイトル': '平成26年台風第11号',
  '災害種別': '台風',
  '適用日': '2014-08-09',
  'municipalities': ['39201', '39344', '39412', '36368']},
 4: {'西暦年度': 2014,
  '災害タイトル': '平成26年台風第12号',
  '災害種別': '台風',
  '適用日': '2014-08-03',
  'municipalities': ['39386']},
 5: {'西暦年度': 2014,
  '災害タイトル': '平成26年台風第８号',
  '災害種別': '台風',
  '適用日': '2014-07-09',
  'municipalities': ['20423', '06213']},
 6: {'西暦年度': 2014,
  '災害タイトル': '御嶽山噴火による被害',
  '災害種別': '噴火',
  '適用日': '2014-09-27',
  'municipalities': ['20432', '20429']},
 7: {'西暦年度': 2014,
  '災害タイトル': '長野県神城断層地震',
  '災害種別': '地震',
  '適用日': '2014-11-22',
  'municipalities': ['20485', '20486', '20588']},
 8: {'西暦年度': 2015,
  '災害タイトル': '口永良部島噴火',
  '災害種別': '噴火',
  '適用日': '2015-05-29',
  'municipalities': ['46505']},
 9: {'西暦年度': 2015,
  '災害タイトル': '平成27年台風第21号',
  '災害種別': '台風',
  '適用日': '2015-09-28',
  'municipalities': ['47382']},
 10: {'西暦年度': 2015,
  '災害タイトル': '平成27年９月関東・東北豪雨',
  '災害種別': '大雨',
  '適用日': '2015-09-09',
  'municipalities': ['08204',
   '08207',
   '08210',
   '08211',
   '08227',
   '08521',
   '08546',
   '08224',
   '08228',
   '08235',
   '09203',
   '09204',
   '09205',
   '09206',
   '09208',
   '09216',
   '09364',
   '09361',
   '04101',
   '04102',
   '04103',
   '04104',
   '04105',
   '04213',
   '04214',
   '04215',
   '04401',
   '04421',
   '04445',
   '04501']},
 11: {'西暦年度': 2016,
  '災害タイトル': '平成28年台風第10号',
  '災害種別': '台風',
  '適用日': '2016-08-30',
  'municipalities': ['01207',
   '01462',
   '01631',
   '01632',
   '01633',
   '01634',
   '01635',
   '01636',
   '01637',
   '01638',
   '01639',
   '01641',
   '01642',
   '01643',
   '01644',
   '01645',
   '01646',
   '01647',
   '01648',
   '01649',
   '03201',
   '03202',
   '03207',
   '03208',
   '03211',
   '03461',
   '03483',
   '03484',
   '03485',
   '03501',
   '03503',
   '03524']},
 12: {'西暦年度': 2016,
  '災害タイトル': '平成28年新潟県糸魚川市における大規模火災（住宅火災）',
  '災害種別': '火災',
  '適用日': '2016-12-22',
  'municipalities': ['15216']},
 13: {'西暦年度': 2016,
  '災害タイトル': '平成28年熊本地震',
  '災害種別': '地震',
  '適用日': '2016-04-14',
  'municipalities': ['43101',
   '43102',
   '43103',
   '43104',
   '43105',
   '43202',
   '43203',
   '43204',
   '43205',
   '43206',
   '43208',
   '43210',
   '43211',
   '43212',
   '43213',
   '43214',
   '43215',
   '43216',
   '43348',
   '43364',
   '43367',
   '43368',
   '43369',
   '43403',
   '43404',
   '43423',
   '43424',
   '43425',
   '43428',
   '43432',
   '43433',
   '43441',
   '43442',
   '43443',
   '43444',
   '43447',
   '43468',
   '43482',
   '43484',
   '43501',
   '43505',
   '43506',
   '43507',
   '43510',
   '43511',
   '43512',
   '43513',
   '43514',
   '43531']},
 14: {'西暦年度': 2016,
  '災害タイトル': '平成28年鳥取県中部地震',
  '災害種別': '地震',
  '適用日': '2016-10-21',
  'municipalities': ['31203', '31370', '31372', '31364']},
 15: {'西暦年度': 2017,
  '災害タイトル': '平成29年7月22日からの大雨',
  '災害種別': '大雨',
  '適用日': '2017-07-22',
  'municipalities': ['05212']},
 16: {'西暦年度': 2017,
  '災害タイトル': '平成29年7月九州北部豪雨',
  '災害種別': '大雨',
  '適用日': '2017-07-05',
  'municipalities': ['40228', '40448', '44204', '44203', '40602']},
 17: {'西暦年度': 2017,
  '災害タイトル': '平成29年台風第18号',
  '災害種別': '台風',
  '適用日': '2017-09-17',
  'municipalities': ['44205', '44207']},
 18: {'西暦年度': 2017,
  '災害タイトル': '平成29年台風第21号',
  '災害種別': '台風',
  '適用日': '2017-10-21',
  'municipalities': ['30207', '24203', '24461', '26202']},
 19: {'西暦年度': 2017,
  '災害タイトル': '平成29年度豪雪',
  '災害種別': '大雪',
  '適用日': '2018-02-14',
  'municipalities': ['15202', '15208', '15210', '15225', '15385']},
 20: {'西暦年度': 2017,
  '災害タイトル': '平成30年2月4日からの大雪',
  '災害種別': '大雪',
  '適用日': '2018-02-06',
  'municipalities': ['18201',
   '18205',
   '18206',
   '18207',
   '18208',
   '18210',
   '18322',
   '18423',
   '18209']},
 21: {'西暦年度': 2018,
  '災害タイトル': '平成30年北海道胆振東部地震',
  '災害種別': '地震',
  '適用日': '2018-09-06',
  'municipalities': ['01101',
   '01102',
   '01103',
   '01104',
   '01105',
   '01106',
   '01107',
   '01108',
   '01109',
   '01110',
   '01202',
   '01203',
   '01204',
   '01205',
   '01206',
   '01207',
   '01208',
   '01209',
   '01210',
   '01211',
   '01212',
   '01213',
   '01214',
   '01215',
   '01216',
   '01217',
   '01218',
   '01219',
   '01220',
   '01221',
   '01222',
   '01223',
   '01224',
   '01225',
   '01226',
   '01227',
   '01228',
   '01229',
   '01230',
   '01231',
   '01233',
   '01234',
   '01235',
   '01236',
   '01303',
   '01304',
   '01331',
   '01332',
   '01333',
   '01334',
   '01337',
   '01343',
   '01345',
   '01346',
   '01347',
   '01361',
   '01362',
   '01363',
   '01364',
   '01367',
   '01370',
   '01371',
   '01391',
   '01392',
   '01393',
   '01394',
   '01395',
   '01396',
   '01397',
   '01398',
   '01399',
   '01400',
   '01401',
   '01402',
   '01403',
   '01404',
   '01405',
   '01406',
   '01407',
   '01408',
   '01409',
   '01423',
   '01424',
   '01425',
   '01427',
   '01428',
   '01429',
   '01430',
   '01431',
   '01432',
   '01433',
   '01434',
   '01436',
   '01437',
   '01438',
   '01452',
   '01453',
   '01454',
   '01455',
   '01456',
   '01457',
   '01458',
   '01459',
   '01460',
   '01461',
   '01462',
   '01463',
   '01464',
   '01465',
   '01468',
   '01469',
   '01470',
   '01471',
   '01472',
   '01481',
   '01482',
   '01483',
   '01484',
   '01485',
   '01486',
   '01487',
   '01511',
   '01512',
   '01513',
   '01514',
   '01516',
   '01517',
   '01518',
   '01519',
   '01520',
   '01543',
   '01544',
   '01545',
   '01546',
   '01547',
   '01549',
   '01550',
   '01552',
   '01555',
   '01559',
   '01560',
   '01561',
   '01562',
   '01563',
   '01564',
   '01571',
   '01575',
   '01578',
   '01581',
   '01584',
   '01585',
   '01586',
   '01601',
   '01602',
   '01604',
   '01607',
   '01608',
   '01609',
   '01610',
   '01631',
   '01632',
   '01633',
   '01634',
   '01635',
   '01636',
   '01637',
   '01638',
   '01639',
   '01641',
   '01642',
   '01643',
   '01644',
   '01645',
   '01646',
   '01647',
   '01648',
   '01649',
   '01661',
   '01662',
   '01663',
   '01664',
   '01665',
   '01667',
   '01668',
   '01691',
   '01692',
   '01693',
   '01694',
   '01695',
   '01696',
   '01697',
   '01698',
   '01699',
   '01700']},
 22: {'西暦年度': 2018,
  '災害タイトル': '平成30年大阪府北部を震源とする地震',
  '災害種別': '地震',
  '適用日': '2018-06-18',
  'municipalities': ['27102',
   '27103',
   '27104',
   '27106',
   '27107',
   '27108',
   '27109',
   '27111',
   '27113',
   '27114',
   '27115',
   '27116',
   '27117',
   '27118',
   '27119',
   '27120',
   '27121',
   '27122',
   '27123',
   '27124',
   '27125',
   '27126',
   '27127',
   '27128',
   '27203',
   '27205',
   '27207',
   '27209',
   '27210',
   '27211',
   '27215',
   '27220',
   '27224',
   '27229',
   '27230',
   '27301']},
 23: {'西暦年度': 2018,
  '災害タイトル': '平成30年７月豪雨',
  '災害種別': '大雨',
  '適用日': '2018-07-05',
  'municipalities': ['26201',
   '26202',
   '26203',
   '26205',
   '26212',
   '26213',
   '26407',
   '26463',
   '26465',
   '38202',
   '38203',
   '38207',
   '38214',
   '38484',
   '38488',
   '31201',
   '31325',
   '31328',
   '31329',
   '32207',
   '39203',
   '39341',
   '33204',
   '35208',
   '28209',
   '28221',
   '28225',
   '28227',
   '28481',
   '28585',
   '33101',
   '33102',
   '33103',
   '33104',
   '33202',
   '33205',
   '33207',
   '33208',
   '33209',
   '33210',
   '33212',
   '33213',
   '33214',
   '33216',
   '33423',
   '33445',
   '33643',
   '33681',
   '33606',
   '34101',
   '34102',
   '34103',
   '34104',
   '34105',
   '34106',
   '34107',
   '34108',
   '28201',
   '28213',
   '28223',
   '28365',
   '28501',
   '34309',
   '39211',
   '28222',
   '28229',
   '28442',
   '28446',
   '31364',
   '31389',
   '31390',
   '31401',
   '31402',
   '31403',
   '34202',
   '34203',
   '34204',
   '34205',
   '34207',
   '34208',
   '34212',
   '34215',
   '34302',
   '34304',
   '34307',
   '21203',
   '21205',
   '21206',
   '21210',
   '21211',
   '21214',
   '21215',
   '21217',
   '21218',
   '21219',
   '21220',
   '21501',
   '21504',
   '21505',
   '21506',
   '21507',
   '21604',
   '21201',
   '21207',
   '21502',
   '21503',
   '33203',
   '33215',
   '39208',
   '39209',
   '39427',
   '39424',
   '40205',
   '32441',
   '34209',
   '34210',
   '33203',
   '40203',
   '33461']},
 24: {'西暦年度': 2018,
  '災害タイトル': '平成30年８月30日からの大雨',
  '災害種別': '大雨',
  '適用日': '2018-08-31',
  'municipalities': ['06205',
   '06362',
   '06363',
   '06364',
   '06365',
   '06366',
   '06367']},
 25: {'西暦年度': 2019,
  '災害タイトル': '令和元年台風第15号',
  '災害種別': '台風',
  '適用日': '2019-09-08',
  'municipalities': ['13361']},
 26: {'西暦年度': 2019,
  '災害タイトル': '令和元年台風第15号（停電）',
  '災害種別': '台風',
  '適用日': '2019-09-09',
  'municipalities': ['12101',
   '12202',
   '12205',
   '12206',
   '12210',
   '12211',
   '12212',
   '12213',
   '12215',
   '12218',
   '12219',
   '12223',
   '12225',
   '12226',
   '12228',
   '12229',
   '12230',
   '12231',
   '12233',
   '12234',
   '12235',
   '12236',
   '12237',
   '12238',
   '12239',
   '12322',
   '12329',
   '12342',
   '12347',
   '12349',
   '12403',
   '12409',
   '12410',
   '12421',
   '12422',
   '12423',
   '12424',
   '12426',
   '12427',
   '12441',
   '12463']},
 27: {'西暦年度': 2019,
  '災害タイトル': '令和元年台風第19号',
  '災害種別': '台風',
  '適用日': '2019-10-12',
  'municipalities': ['07203',
   '07204',
   '07205',
   '07207',
   '07209',
   '07210',
   '07211',
   '07212',
   '07342',
   '07344',
   '07364',
   '07367',
   '07368',
   '07461',
   '07464',
   '07465',
   '07481',
   '07483',
   '07484',
   '07501',
   '07502',
   '07503',
   '07504',
   '07505',
   '07521',
   '07522',
   '07541',
   '07542',
   '07543',
   '07544',
   '07545',
   '07546',
   '07547',
   '07548',
   '07561',
   '07564',
   '08202',
   '08205',
   '08212',
   '08214',
   '08215',
   '08216',
   '08225',
   '08231',
   '08310',
   '08364',
   '09201',
   '09202',
   '09203',
   '09204',
   '09205',
   '09206',
   '09210',
   '09211',
   '09213',
   '09214',
   '09384',
   '09386',
   '09407',
   '09411',
   '10201',
   '10202',
   '10203',
   '10205',
   '10206',
   '10207',
   '10208',
   '10209',
   '10210',
   '10211',
   '10212',
   '10345',
   '10366',
   '10367',
   '10382',
   '10383',
   '10384',
   '10421',
   '10424',
   '10425',
   '10426',
   '10428',
   '10429',
   '10449',
   '10523',
   '10525',
   '11202',
   '11207',
   '11209',
   '11211',
   '11212',
   '11215',
   '11218',
   '11225',
   '11239',
   '11242',
   '11326',
   '11327',
   '11341',
   '11342',
   '11343',
   '11346',
   '11347',
   '11348',
   '11349',
   '11361',
   '11362',
   '11363',
   '11365',
   '11369',
   '11381',
   '11383',
   '11408',
   '13116',
   '13117',
   '13119',
   '13120',
   '13201',
   '13202',
   '13205',
   '13206',
   '13207',
   '13209',
   '13210',
   '13212',
   '13218',
   '13220',
   '13223',
   '13224',
   '13225',
   '13227',
   '13228',
   '13303',
   '13305',
   '13307',
   '13308',
   '14131',
   '14132',
   '14133',
   '14134',
   '14135',
   '14136',
   '14137',
   '14151',
   '14152',
   '14153',
   '14203',
   '14206',
   '14207',
   '14211',
   '14212',
   '14214',
   '14215',
   '14216',
   '14217',
   '14321',
   '14362',
   '14363',
   '14364',
   '14382',
   '14384',
   '14401',
   '14402',
   '19202',
   '19204',
   '19205',
   '19206',
   '19207',
   '19208',
   '19209',
   '19211',
   '19212',
   '19213',
   '19346',
   '19364',
   '19365',
   '19366',
   '19368',
   '19422',
   '19429',
   '19430',
   '19442',
   '19443',
   '20201',
   '20202',
   '20203',
   '20204',
   '20206',
   '20207',
   '20208',
   '20209',
   '20211',
   '20213',
   '20214',
   '20217',
   '20218',
   '20219',
   '20220',
   '20303',
   '20304',
   '20305',
   '20306',
   '20307',
   '20309',
   '20321',
   '20323',
   '20324',
   '20349',
   '20350',
   '20361',
   '20362',
   '20382',
   '20388',
   '20432',
   '20446',
   '20448',
   '20452',
   '20521',
   '20541',
   '20543',
   '20561',
   '20562',
   '20590',
   '20602',
   '22225',
   '22325',
   '03202',
   '03203',
   '03207',
   '03209',
   '03210',
   '03211',
   '03441',
   '03461',
   '03482',
   '03483',
   '03484',
   '03485',
   '03503',
   '03507',
   '04101',
   '04102',
   '04103',
   '04104',
   '04105',
   '04202',
   '04203',
   '04205',
   '04206',
   '04207',
   '04208',
   '04209',
   '04211',
   '04212',
   '04213',
   '04214',
   '04215',
   '04216',
   '04301',
   '04302',
   '04321',
   '04322',
   '04323',
   '04324',
   '04341',
   '04361',
   '04362',
   '04401',
   '04404',
   '04406',
   '04421',
   '04422',
   '04424',
   '04444',
   '04445',
   '04501',
   '04505',
   '04581',
   '04606',
   '07201',
   '07202',
   '07213',
   '07214',
   '07301',
   '07303',
   '07308',
   '07322',
   '07362',
   '07423',
   '07444',
   '07445',
   '07447',
   '07466',
   '13107',
   '13112',
   '15222',
   '15216',
   '15217',
   '20215',
   '20363',
   '20563',
   '09215',
   '09208',
   '09216',
   '09301',
   '09343',
   '09344',
   '09361',
   '10204',
   '10344',
   '10464',
   '10524',
   '13111',
   '13208',
   '13219',
   '08201',
   '08203',
   '08207',
   '08211',
   '08220',
   '08221',
   '08224',
   '08226',
   '08227',
   '08228',
   '08230',
   '11101',
   '11102',
   '11103',
   '11104',
   '11105',
   '11106',
   '11107',
   '11108',
   '11109',
   '11110',
   '11201',
   '11203',
   '11206',
   '11208',
   '11227',
   '11228',
   '11229',
   '11230',
   '11235',
   '11241',
   '11324',
   '11385',
   '08232',
   '08302',
   '08204',
   '08210',
   '08234',
   '08235',
   '08309',
   '08521',
   '08546',
   '11214',
   '11219',
   '11222',
   '11223',
   '11224',
   '11231',
   '11234',
   '11245']},
 28: {'西暦年度': 2019,
  '災害タイトル': '令和元年８月の前線に伴う大雨',
  '災害種別': '大雨',
  '適用日': '2019-08-28',
  'municipalities': ['41201',
   '41202',
   '41203',
   '41204',
   '41205',
   '41206',
   '41207',
   '41208',
   '41209',
   '41210',
   '41327',
   '41341',
   '41345',
   '41346',
   '41387',
   '41401',
   '41423',
   '41424',
   '41425',
   '41441']},
 29: {'西暦年度': 2020,
  '災害タイトル': '令和２年12月16日からの大雪（交通障害）',
  '災害種別': '大雪',
  '適用日': '2020-12-17',
  'municipalities': ['15226', '15461']},
 30: {'西暦年度': 2020,
  '災害タイトル': '令和２年台風第14号',
  '災害種別': '台風',
  '適用日': '2020-10-10',
  'municipalities': ['13381', '13382']},
 31: {'西暦年度': 2020,
  '災害タイトル': '令和２年７月３日からの大雨',
  '災害種別': '大雨',
  '適用日': '2020-07-04',
  'municipalities': ['43202',
   '43203',
   '43205',
   '43212',
   '43215',
   '43482',
   '43484',
   '43501',
   '43505',
   '43506',
   '43507',
   '43510',
   '43511',
   '43512',
   '43513',
   '43514',
   '46206',
   '46208',
   '46224',
   '46404',
   '40202',
   '40210',
   '40229',
   '46203',
   '46217',
   '46221',
   '43204',
   '43206',
   '43208',
   '43210',
   '43364',
   '43367',
   '43368',
   '43369',
   '43423',
   '43424',
   '40203',
   '20202',
   '20205',
   '20209',
   '20220',
   '20388',
   '20404',
   '20407',
   '20411',
   '20412',
   '20422',
   '20423',
   '20429',
   '20430',
   '20432',
   '21203',
   '21206',
   '21210',
   '21217',
   '21219',
   '21220',
   '41207',
   '44213',
   '44461',
   '44462',
   '32207',
   '44204',
   '46214',
   '46215',
   '46219',
   '46468',
   '06201',
   '06202',
   '06203',
   '06204',
   '06205',
   '06206',
   '06207',
   '06208',
   '06209',
   '06210',
   '06211',
   '06212',
   '06213',
   '06301',
   '06302',
   '06321',
   '06322',
   '06323',
   '06324',
   '06341',
   '06362',
   '06363',
   '06365',
   '06367',
   '06381',
   '06382',
   '06401',
   '06402',
   '06403',
   '06426',
   '06428']},
 32: {'西暦年度': 2020,
  '災害タイトル': '令和３年新潟県糸魚川市における地滑り',
  '災害種別': '地滑り',
  '適用日': '2021-03-04',
  'municipalities': ['15216']},
 33: {'西暦年度': 2020,
  '災害タイトル': '令和３年栃木県足利市における大規模火災（山林火災）',
  '災害種別': '火災',
  '適用日': '2021-02-23',
  'municipalities': ['09202']},
 34: {'西暦年度': 2020,
  '災害タイトル': '令和３年福島県沖を震源とする地震',
  '災害種別': '地震',
  '適用日': '2021-02-13',
  'municipalities': ['07201',
   '07203',
   '07205',
   '07207',
   '07209',
   '07212',
   '07213',
   '07214',
   '07301',
   '07303',
   '07342',
   '07447',
   '07541',
   '07542',
   '07543',
   '07547',
   '07561']},
 35: {'西暦年度': 2020,
  '災害タイトル': '令和３年１月７日からの大雪',
  '災害種別': '大雪',
  '適用日': '2021-01-07',
  'municipalities': ['05203',
   '05207',
   '05212',
   '05215',
   '05434',
   '05463',
   '05464',
   '16208',
   '16209',
   '16210',
   '16205',
   '18201',
   '18208',
   '18210',
   '15202',
   '15205',
   '15210',
   '15216',
   '15217',
   '15222',
   '18205',
   '18206']},
 36: {'西暦年度': 2021,
  '災害タイトル': '令和３年長野県茅野市において発生した土石流',
  '災害種別': '土石流',
  '適用日': '2021-09-05',
  'municipalities': ['20214']},
 37: {'西暦年度': 2021,
  '災害タイトル': '令和３年７月１日からの大雨',
  '災害種別': '大雨',
  '適用日': '2021-07-03',
  'municipalities': ['22205',
   '31201',
   '32201',
   '32203',
   '46208',
   '46215',
   '46224',
   '46392',
   '46452']},
 38: {'西暦年度': 2021,
  '災害タイトル': '令和３年８月１１日からの大雨',
  '災害種別': '大雨',
  '適用日': '2021-08-12',
  'municipalities': ['32207',
   '42213',
   '40203',
   '41206',
   '41209',
   '41423',
   '42214',
   '40210',
   '40229',
   '34106',
   '34214',
   '34369',
   '34101',
   '34102',
   '34103',
   '34104',
   '34105',
   '34106',
   '34107',
   '34108',
   '34209',
   '32441',
   '32448',
   '20204',
   '20206',
   '20382',
   '20422',
   '20429',
   '20432']},
 39: {'西暦年度': 2021,
  '災害タイトル': '台風第９号から変わった温帯低気圧に伴う大雨',
  '災害種別': '大雨',
  '適用日': '2021-08-10',
  'municipalities': ['02208', '02402', '02425']},
 40: {'西暦年度': 2021,
  '災害タイトル': '島根県松江市における大規模火災（住宅火災）',
  '災害種別': '火災',
  '適用日': '2021-04-01',
  'municipalities': ['32201']},
 41: {'西暦年度': 2022,
  '災害タイトル': '令和４年12月17日からの大雪（交通障害等）',
  '災害種別': '大雪',
  '適用日': '2022-12-19',
  'municipalities': ['15205', '15202', '15208', '15225']},
 42: {'西暦年度': 2022,
  '災害タイトル': '令和４年12月22日からの大雪（長期停電）',
  '災害種別': '大雪',
  '適用日': '2022-12-22',
  'municipalities': ['15224',
   '01208',
   '01219',
   '01514',
   '01543',
   '01545',
   '01546',
   '01555',
   '01559',
   '01561',
   '01563',
   '15212']},
 43: {'西暦年度': 2022,
  '災害タイトル': '令和４年台風第14号',
  '災害種別': '台風',
  '適用日': '2022-09-17',
  'municipalities': ['46201',
   '46203',
   '46204',
   '46206',
   '46208',
   '46210',
   '46213',
   '46214',
   '46215',
   '46216',
   '46217',
   '46218',
   '46219',
   '46220',
   '46221',
   '46222',
   '46223',
   '46224',
   '46225',
   '46303',
   '46304',
   '46392',
   '46404',
   '46452',
   '46468',
   '46482',
   '46490',
   '46491',
   '46492',
   '46501',
   '46502',
   '46505',
   '46523',
   '46524',
   '46525',
   '46527',
   '46529',
   '46530',
   '46531',
   '46532',
   '46533',
   '46534',
   '46535',
   '40101',
   '40103',
   '40105',
   '40106',
   '40107',
   '40108',
   '40109',
   '40131',
   '40132',
   '40133',
   '40134',
   '40135',
   '40136',
   '40137',
   '40202',
   '40203',
   '40204',
   '40205',
   '40206',
   '40207',
   '40210',
   '40211',
   '40212',
   '40213',
   '40214',
   '40215',
   '40216',
   '40217',
   '40218',
   '40219',
   '40220',
   '40221',
   '40223',
   '40224',
   '40225',
   '40226',
   '40227',
   '40228',
   '40229',
   '40230',
   '40231',
   '40341',
   '40342',
   '40343',
   '40344',
   '40345',
   '40348',
   '40349',
   '40381',
   '40382',
   '40383',
   '40384',
   '40401',
   '40402',
   '40421',
   '40447',
   '40448',
   '40503',
   '40522',
   '40544',
   '40601',
   '40602',
   '40604',
   '40605',
   '40608',
   '40609',
   '40610',
   '40621',
   '40625',
   '40642',
   '40646',
   '40647',
   '43101',
   '43102',
   '43103',
   '43104',
   '43105',
   '43202',

In [93]:
disaster_summary

{'01101': {'name': '北海道 札幌市中央区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01102': {'name': '北海道 札幌市北区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01103': {'name': '北海道 札幌市東区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01104': {'name': '北海道 札幌市白石区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01105': {'name': '北海道 札幌市豊平区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01106': {'name': '北海道 札幌市南区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01107': {'name': '北海道 札幌市西区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01108': {'name': '北海道 札幌市厚別区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01109': {'name': '北海道 札幌市手稲区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01110': {'name': '北海道 札幌市清田区',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01202': {'name': '北海道 函館市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01203': {'name': '北海道 小樽市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01204': {'name': '北海道 旭川市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01205': {'name': '北海道 室蘭市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01206': {'name': '北海道 釧路市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01207': {'name': '北海道 帯広市',
  'disaster_id': [11, 21],
  'disaster_count': {'台風': 1,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 2}},
 '01208': {'name': '北海道 北見市',
  'disaster_id': [21, 42, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 1,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 3}},
 '01209': {'name': '北海道 夕張市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01210': {'name': '北海道 岩見沢市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01211': {'name': '北海道 網走市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01212': {'name': '北海道 留萌市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01213': {'name': '北海道 苫小牧市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01214': {'name': '北海道 稚内市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01215': {'name': '北海道 美唄市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01216': {'name': '北海道 芦別市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01217': {'name': '北海道 江別市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01218': {'name': '北海道 赤平市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01219': {'name': '北海道 紋別市',
  'disaster_id': [21, 42, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 1,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 3}},
 '01220': {'name': '北海道 士別市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01221': {'name': '北海道 名寄市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01222': {'name': '北海道 三笠市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01223': {'name': '北海道 根室市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01224': {'name': '北海道 千歳市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01225': {'name': '北海道 滝川市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01226': {'name': '北海道 砂川市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01227': {'name': '北海道 歌志内市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01228': {'name': '北海道 深川市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01229': {'name': '北海道 富良野市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01230': {'name': '北海道 登別市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01231': {'name': '北海道 恵庭市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01233': {'name': '北海道 伊達市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01234': {'name': '北海道 北広島市',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01235': {'name': '北海道 石狩市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01236': {'name': '北海道 北斗市',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01303': {'name': '北海道 当別町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01304': {'name': '北海道 新篠津村',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01331': {'name': '北海道 松前町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01332': {'name': '北海道 福島町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01333': {'name': '北海道 知内町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01334': {'name': '北海道 木古内町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01337': {'name': '北海道 七飯町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01343': {'name': '北海道 鹿部町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01345': {'name': '北海道 森町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01346': {'name': '北海道 八雲町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01347': {'name': '北海道 長万部町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01361': {'name': '北海道 江差町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01362': {'name': '北海道 上ノ国町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01363': {'name': '北海道 厚沢部町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01364': {'name': '北海道 乙部町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01367': {'name': '北海道 奥尻町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01370': {'name': '北海道 今金町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01371': {'name': '北海道 せたな町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01391': {'name': '北海道 島牧村',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01392': {'name': '北海道 寿都町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01393': {'name': '北海道 黒松内町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01394': {'name': '北海道 蘭越町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01395': {'name': '北海道 ニセコ町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01396': {'name': '北海道 真狩村',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01397': {'name': '北海道 留寿都村',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01398': {'name': '北海道 喜茂別町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01399': {'name': '北海道 京極町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01400': {'name': '北海道 倶知安町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01401': {'name': '北海道 共和町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01402': {'name': '北海道 岩内町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01403': {'name': '北海道 泊村',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01404': {'name': '北海道 神恵内村',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01405': {'name': '北海道 積丹町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01406': {'name': '北海道 古平町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01407': {'name': '北海道 仁木町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01408': {'name': '北海道 余市町',
  'disaster_id': [21, 72],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 1,
   '合計': 2}},
 '01409': {'name': '北海道 赤井川村',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01423': {'name': '北海道 南幌町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01424': {'name': '北海道 奈井江町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01425': {'name': '北海道 上砂川町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01427': {'name': '北海道 由仁町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01428': {'name': '北海道 長沼町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01429': {'name': '北海道 栗山町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01430': {'name': '北海道 月形町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,
   '合計': 1}},
 '01431': {'name': '北海道 浦臼町',
  'disaster_id': [21],
  'disaster_count': {'台風': 0,
   '大雨': 0,
   '噴火': 0,
   '地震': 1,
   '大雪': 0,
   '火災': 0,
   '地滑り': 0,
   '土石流': 0,
   '土砂崩れ': 0,
   '道路陥没': 0,
   '津波': 0,

In [94]:
# JSONとして保存

# 保存するためのフォルダを作成
os.makedirs('disaster_data', exist_ok=True)

with open(os.path.join('disaster_data', 'disaster_database.json'), 'w', encoding='utf-8') as f:
    json.dump(disaster_database_dict, f, ensure_ascii=False, indent=4)
with open(os.path.join('disaster_data', 'disaster_summary.json'), 'w', encoding='utf-8') as f:
    json.dump(disaster_summary, f, ensure_ascii=False, indent=4)

japan_map.to_file(os.path.join('disaster_data', 'japan_map.geojson'), driver='GeoJSON', encoding='utf-8')